// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from 'prisma/config';

import './envConfig';

export default defineConfig({
  schema: 'src/shared/prisma/schema.prisma',
  migrations: {
    path: 'src/shared/prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
